stages:
  tuto:
    cmd: python main.py -cd=xps/tuto/sota/.hydra -cn=config hydra.run.dir=xps/tuto/sota
    deps:
    - data/my_dep.csv
    outs:
    - xps/tuto/sota/outs/out.csv
    params:
    - xps/tuto/sota/.hydra/config.yaml:
      - params.my_param
